# Generated by Django 3.2 on 2022-10-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsspu',
            name='select',
            field=models.IntegerField(null=True),
        ),
    ]
