# Generated by Django 3.2 on 2022-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_goodsspu_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='sp_picture',
            field=models.ImageField(upload_to='./uploads/thumb/605_605'),
        ),
    ]
