# Generated by Django 3.2 on 2022-10-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='user_order_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order_mes_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_center.ordermessage'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='sku_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodssku'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
